"""Local HTML dashboard aggregating every run in a results directory.

Reads ``leaderboard.csv`` (stdlib only), renders a sortable table with the
headline metrics of every run, and links each row to its ``report.html``.
No server, no dependencies — a single file for browsing experiments.
"""

from __future__ import annotations

import csv
import html
from datetime import datetime, timezone
from pathlib import Path

import e2am
from e2am.exceptions import ReportError
from e2am.utils.logging import get_logger

logger = get_logger("reports.dashboard")

#: Leaderboard columns surfaced on the dashboard, in display order.
_PREFERRED_COLUMNS = [
    "run_name",
    "project",
    "status",
    "best_val_accuracy",
    "total_energy_wh",
    "emissions_g",
    "green_score",
    "epochs_completed",
    "duration_s",
    "avg_power_w",
]

_CSS = """
body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
       background: #f9f9f7; color: #0b0b0b; margin: 0; }
main { max-width: 1100px; margin: 0 auto; padding: 32px 24px 64px; }
h1 { font-size: 22px; margin-bottom: 4px; }
.subtitle { color: #52514e; font-size: 13px; margin-bottom: 24px; }
table { border-collapse: collapse; width: 100%; background: #fcfcfb;
        border: 1px solid rgba(11,11,11,0.10); font-size: 13px; }
th { text-align: left; padding: 8px 12px; color: #52514e; cursor: pointer;
     border-bottom: 2px solid #e1e0d9; user-select: none; white-space: nowrap; }
th:hover { color: #0b0b0b; }
td { padding: 7px 12px; border-top: 1px solid #e1e0d9;
     font-variant-numeric: tabular-nums; white-space: nowrap; }
a { color: #1c5cab; text-decoration: none; }
a:hover { text-decoration: underline; }
footer { margin-top: 32px; color: #898781; font-size: 12px; }
"""

_SORT_JS = """
document.querySelectorAll('th').forEach((th, col) => th.addEventListener('click', () => {
  const tbody = th.closest('table').querySelector('tbody');
  const dir = th.dataset.dir === 'asc' ? -1 : 1;
  document.querySelectorAll('th').forEach(h => delete h.dataset.dir);
  th.dataset.dir = dir === 1 ? 'asc' : 'desc';
  Array.from(tbody.querySelectorAll('tr'))
    .sort((a, b) => {
      const av = a.children[col].textContent, bv = b.children[col].textContent;
      const an = parseFloat(av), bn = parseFloat(bv);
      const cmp = (!isNaN(an) && !isNaN(bn)) ? an - bn : av.localeCompare(bv);
      return cmp * dir;
    })
    .forEach(tr => tbody.appendChild(tr));
}));
"""


def generate_dashboard(results_root: str | Path) -> Path:
    """Build ``dashboard.html`` inside ``results_root`` and return its path.

    Raises:
        ReportError: If no leaderboard exists yet (no finished runs).
    """
    results_root = Path(results_root)
    leaderboard = results_root / "leaderboard.csv"
    if not leaderboard.exists():
        raise ReportError(
            f"No leaderboard at {leaderboard}. Finish at least one monitored "
            "run (or `e2am report <run_dir>`) first."
        )
    with open(leaderboard, newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ReportError(f"Leaderboard {leaderboard} is empty.")

    all_columns = list(rows[0].keys())
    columns = [c for c in _PREFERRED_COLUMNS if c in all_columns]
    columns += [c for c in all_columns if c not in columns]

    head = "".join(f"<th>{html.escape(c)}</th>" for c in columns)
    body_rows = []
    for row in rows:
        cells = []
        for column in columns:
            value = html.escape(row.get(column, ""))
            if column == "run_name":
                report = results_root / row.get(column, "") / "report.html"
                if report.exists():
                    value = f'<a href="{html.escape(row[column])}/report.html">{value}</a>'
            cells.append(f"<td>{value}</td>")
        body_rows.append(f"<tr>{''.join(cells)}</tr>")

    document = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<title>E2AM dashboard</title>"
        f"<style>{_CSS}</style></head><body><main>"
        "<h1>E2AM dashboard</h1>"
        f'<div class="subtitle">{len(rows)} run(s) · {html.escape(str(results_root))} · '
        f"generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · "
        "click a column header to sort</div>"
        f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"
        f"<footer>Generated by E2AM v{e2am.__version__}</footer>"
        f"</main><script>{_SORT_JS}</script></body></html>"
    )
    path = results_root / "dashboard.html"
    path.write_text(document, encoding="utf-8")
    logger.info("Dashboard written to %s", path)
    return path
