"""Self-contained HTML report generation.

The report is a single file: plots are embedded as base64 data URIs and the
CSS is inlined, so it can be emailed, archived, or opened offline and never
break. Styling reuses the chart chrome tokens for a coherent look.
"""

from __future__ import annotations

import base64
import html
from datetime import datetime, timezone
from pathlib import Path

import e2am
from e2am.reports.common import AnyResult, build_sections
from e2am.utils.logging import get_logger

logger = get_logger("reports.html")

_CSS = """
:root { color-scheme: light; }
body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
       background: #f9f9f7; color: #0b0b0b; margin: 0; }
main { max-width: 900px; margin: 0 auto; padding: 32px 24px 64px; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 15px; margin: 32px 0 8px; color: #0b0b0b; }
.subtitle { color: #52514e; font-size: 13px; margin-bottom: 24px; }
table { border-collapse: collapse; width: 100%; background: #fcfcfb;
        border: 1px solid rgba(11,11,11,0.10); border-radius: 6px; }
td { padding: 6px 12px; font-size: 13px; border-top: 1px solid #e1e0d9; }
tr:first-child td { border-top: none; }
td.label { color: #52514e; width: 40%; }
td.value { font-variant-numeric: tabular-nums; }
.plot { margin: 12px 0; background: #fcfcfb; border: 1px solid rgba(11,11,11,0.10);
        border-radius: 6px; padding: 8px; }
.plot img { max-width: 100%; height: auto; display: block; }
footer { margin-top: 40px; color: #898781; font-size: 12px; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 10px;
         font-size: 12px; background: #e7f0fb; color: #1c5cab; }
.badge.failed { background: #fbe9e9; color: #a32626; }
"""


def _embed_png(path: Path) -> str:
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:image/png;base64,{data}"


def generate_html_report(
    result: AnyResult,
    run_dir: str | Path,
    plots: list[Path] | None = None,
) -> Path:
    """Write ``report.html`` into ``run_dir`` and return its path.

    Args:
        result: A training or monitoring result.
        run_dir: The run's artifact directory.
        plots: Plot PNGs to embed; defaults to every ``*.png`` in ``run_dir``.
    """
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    if plots is None:
        plots = sorted(run_dir.glob("*.png"))

    parts: list[str] = ["<main>"]
    badge_class = "badge failed" if result.status == "failed" else "badge"
    parts.append(f"<h1>{html.escape(result.project)} / {html.escape(result.run_name)} ")
    parts.append(f'<span class="{badge_class}">{html.escape(result.status)}</span></h1>')
    parts.append(
        '<div class="subtitle">E2AM experiment report · generated '
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>"
    )

    for title, rows in build_sections(result):
        parts.append(f"<h2>{html.escape(title)}</h2><table>")
        for label, value in rows:
            parts.append(
                f'<tr><td class="label">{html.escape(label)}</td>'
                f'<td class="value">{html.escape(value)}</td></tr>'
            )
        parts.append("</table>")

    if plots:
        parts.append("<h2>Charts</h2>")
        for plot in plots:
            if plot.exists():
                parts.append(
                    f'<div class="plot"><img alt="{html.escape(plot.stem)}" '
                    f'src="{_embed_png(plot)}"></div>'
                )

    parts.append(
        f"<footer>Generated by <b>E2AM</b> v{e2am.__version__} — "
        'Energy Efficient AI Models · <a href="https://github.com/Shanmuk4622/e2am">'
        "github.com/Shanmuk4622/e2am</a></footer></main>"
    )

    document = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{html.escape(result.project)} / {html.escape(result.run_name)} · E2AM</title>"
        f"<style>{_CSS}</style></head><body>{''.join(parts)}</body></html>"
    )
    path = run_dir / "report.html"
    path.write_text(document, encoding="utf-8")
    logger.debug("Wrote HTML report to %s", path)
    return path
